//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		abstract public class Action
		{
		public string type;
		public Unit unit;
				public Action ()
				{
					
				}

		public void start(){
			Grid.controller.startingAction(this);
		}

		public abstract void display(); //shows selectable tiles
		public abstract void activate(Tile tile); //does the action
		public abstract void clickedTile(Tile tile);	//input from user
		public abstract void rightClickedTile(Tile tile); //input from user
		public abstract float evaluate(); //for AI use
		}
}

