//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class EndTurn : Action
		{
				public EndTurn (Unit u)
				{
					type = "End";
					unit = u;
				}

		public override void display(){ //shows selectable tiles
			activate (null);
		}
		public override void activate(Tile tile){ //does the action
			unit.mov = 0;
			if (unit.faction.Equals(Grid.turnManager.factions[0])){ //if it was the player's unit.
				unit.deleteActionsMenu();
				unit.refreshVision();
				Grid.controller.endAction("finish");
			}
		}
		public override void clickedTile(Tile tile){	//input from user

		}
		public override void rightClickedTile(Tile tile){ //input from user

		}
		public override float evaluate(){ //for AI use
			return 0f;
		}
		}
}

