//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace AssemblyCSharp
{
		public class AttackUpMaker : SkillMaker
		{
				public AttackUpMaker () : base()
				{
					targets.Add("basic");
					description = "+3 attack";
				}

				public override void giveSkill(Unit unit){
					new PlusAttackSkill(unit,3);
				}
		}
}

