//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	public class DoubleExpSkill : Skill
	{
			public DoubleExpSkill (GameState state, GameObject gameObject) : base(state,gameObject)
			{
			activates.Add ("gainExp");
			}

		//will be called with the value of the amount of exp gained.
		public void activate(string activator){
			int exp = int.Parse(activator);

			unit.exp += exp; //only once since the exp gain already happens once.
		}
	}
}

