//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class FirstStrikeMaker : SkillMaker
		{
				public FirstStrikeMaker () : base()
				{
					targets.Add("basic");
					description = "always attack first in combat";
				}

				public override void giveSkill(Unit unit){
					new FirstStrike(unit);
				}
		}
}

