//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

//provides a unit with an attack boost while it is active.

namespace AssemblyCSharp
{
		public class PlusAttackSkill : Skill {
		public int atkIncrease;
				public PlusAttackSkill (GameState state, GameObject gameObject, int startingValue) : base(state,gameObject)
				{
					atkIncrease = startingValue;
					activate ("start");
				}

				public void activate(string activator){
					unit.atk += atkIncrease;
				}

				public void destroy(string condition){
					unit.atk -= atkIncrease;
				}
		}
}

