//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

//determines the preset skills that appear during the skill phase.
namespace AssemblyCSharp
{
		public abstract class SkillMaker
		{
		public string description = "default"; //text that appears when the skill can be chosen during the skill phase.
		public List<string> targets; //the types of units that this will apply to.

				public SkillMaker ()
				{
					targets = new List<string>();
				}

		//gives the skill to the unit
		public abstract void giveSkill(Unit unit);

		//applies the skill to all applicable units in the player's faction.
		public void giveToAllUnits(){
			foreach (Unit unit in Grid.turnManager.player.units){
				if (targets.Contains(unit.type)){
					giveSkill (unit);
				}
			}
		}

		}
}

