//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using AssemblyCSharp;
using System.Collections.Generic;

namespace AssemblyCSharp
{
		public class GameOptions
		{
			public  int[,] options;

			public GameOptions ()
			{
				options = new int[Map.WIDTH,Map.HEIGHT];
			}

			public int get(int x, int y){
				return options[x,y];
			}

		public void set(int x, int y, int move){
			options[x,y] = move;
		}

		}

}

