//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
namespace AssemblyCSharp
{
		public class TileCosts
		{
		public Hashtable costs;

		public static TileCosts Basic = new TileCosts();
		public static TileCosts Flat;

				static TileCosts(){
					Flat = new TileCosts();
					Flat.costs["Forest"] = 1;
					Flat.costs["Forest"] = 1;
					Flat.costs["Water"] = 1;
				}

				public TileCosts ()
				{
					costs = new Hashtable();
					costs.Add("Grass",1);
					costs.Add("Forest",2);
					costs.Add ("Water",10000);
					//int test = (int) costs["Water"];
				}

		public void change(string type,int cost){
			costs[type] = cost;
		}

		}
}

