//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Chunk{
		
		public static float STRENGTHVARIANCE = 10; //determines by how much the strengths of chunks can vary
		
		//chance is the weight of that type being chosen. Strength effects how far it spreads linearly. Falloff affects how sharply it cuts out.
		//If you want sharp borders between the terrain types while keeping the area about the same size, increase falloff and strength.
		//If you want gradual borders reduce strength and reduce falloff.
		//falloff is more powerfull than strength (exponential compared to linear).
		public static float WATERCHANCE = 1;
		public static float WATERSTRENGTH = 3;
		public static float GRASSCHANCE = 8;
		public static float GRASSSTRENGTH = 7;
		public static float FORESTCHANCE = 3;
		public static float FORESTSTRENGTH = 1;
		//water,grass,forest
		//public static float[] FALLOFFS = new float[3] {4	,1,		1};
		public static Dictionary<string,float> FALLOFF = new Dictionary<string,float> {{"water",4},{"grassland",1.3f},{"forest",2}};
		
		public static float TOTALWEIGHTS = WATERCHANCE + GRASSCHANCE + FORESTCHANCE;
		
		public string type;
		public float strength;
		public int x;
		public int y;
		public static string[] types = new string[3] {"water","forest","grassland"};
		
		public Chunk(int xcor, int ycor){
			x = xcor;
			y = ycor;
			float random = UnityEngine.Random.value;
			if (random < GRASSCHANCE/TOTALWEIGHTS) {type = "grassland"; strength = GRASSSTRENGTH;}
			else if (random < (GRASSCHANCE + WATERCHANCE)/TOTALWEIGHTS) {type = "water"; strength = WATERSTRENGTH;}
			else if (random < (GRASSCHANCE + WATERCHANCE + FORESTCHANCE)/TOTALWEIGHTS) {type = "forest"; strength = FORESTSTRENGTH;}
		}
		
		public void printvalues(){
			//print("xcor: " + x + ". ycor: " + y + ". type: " + type + ". strength: " + strength + ".");
		}
	}
}

