//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class ForestBiome : Biome
		{

		public ForestBiome (int xcor, int ycor) : base(xcor,ycor)
		{
			type = "forest";
			variance = 10;
			strength = 50;
			falloff = 3f;
		}
		
		public override void makeFeatures(){
			
		}
		}
}

