//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class WaterBiome : Biome
		{
		public WaterBiome (int xcor, int ycor) : base(xcor,ycor)
		{
			type = "water";
			variance = 10;
			strength = 3000;
			falloff = 5f;
		}
		
		public override void makeFeatures(){
			
		}
		}
}

