//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
		public class BuildPhase : Phase
		{
				public BuildPhase ()
				{
					type = "Build";
				}

				public override void display(){

					if (activated == true) return; //do not display if the phase is over.

					Grid.turnManager.player.phase = this;
			
					Vector3 start = new Vector3(Grid.camera.transform.position.x,Grid.camera.transform.position.y,1);
					GUIlist list = MonoBehaviour.Instantiate(Grid.prefabLoader.guiList,start,Quaternion.identity) as GUIlist;
					list.transform.SetParent(Grid.camera.transform,true);

					foreach (BuildingEffect effect in Grid.turnManager.player.discoveredBuildings){
						list.addAction(new BuildingMaker(effect)); //TODO exclude those the player cannot afford.
					}
				}

				public override void activate(Tile tile){
					
				}
		}
}

