//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
		public abstract class Phase : Action
		{

				public bool activated; //has this phase been used this age
				public Phase ()
				{
					activated = false;
				}


		public override void clickedTile (Tile tile){
			
		}
		
		public override void rightClickedTile (Tile tile){
			
		}
		
		public override float evaluate (){
			return 0f;
		}
		//public abstract void activate();
				//public abstract void display();
				
		}
}

