//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace AssemblyCSharp
{
		abstract public class Faction
		{
		public string name;
		public List<Unit> units;

				public Faction ()
				{
			units = new List<Unit>();
				}

		public abstract void endTurn();

		public void startTurn(){
			foreach(Unit unit in units){
				unit.mov = unit.maxMov;
			}
		}

		public void addUnit(Unit unit){
			unit.faction = this;
			units.Add(unit);
		}

		}
}

