//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class PlayerFaction : Faction
		{
		Controller controller;
				public PlayerFaction (Controller c) : base()
				{
			controller = c;
				}

		public void startTurn(){
			base.startTurn(); //does this work?
			//controller.enabled = true;
		}

		public override void endTurn(){
			Controller.print("end");
			controller.enabled = false;
		}


		}
}

