//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
		public class Citadel : BuildingEffect
		{
				public Citadel (int x ,int y) : base(x,y)
				{
					activates.Add("MakeUnit");
				}

				public override void activate(string activator){
					
				}

				public override void onCreate(){

				}

				public override void destroy(string condition){
					MonoBehaviour.print ("game over"); //TODO make this more official.
				}
		}
}

