//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

 namespace AssemblyCSharp
{
	public class Market : BuildingEffect
	{

		public Market() : base(){
			name = "Market";
			//activate ("start");
		}

		public Market (int x,int y) : base(x,y)
		{
			name = "Market";
			//activates.Add("");
			onCreate ();
		}
		
		public override void activate(string activator){

		}

		public override void onCreate(){
			Grid.turnManager.player.baseGold += 1;
		}
		
		public override void destroy(string condition){
			Grid.turnManager.player.baseGold -= 1;
		}
}
}


